# https://hub.docker.com/r/oracleinanutshell/oracle-xe-11g
version: "3.7" # 파일 규격 버전
volumes:
  database:
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의 ( 컴포즈에서 컨테이너 : 서비스 )
  db: # 서비스 명
    image: oracleinanutshell/oracle-xe-11g:latest # 사용할 이미지
    restart: always
    container_name: oracle-toy-db # 컨테이너 이름 설정
    ports:
      - 1521:1521
      - 5500:5500 # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)  <- 컨테이너 내부는 무조건 3306
    environment: # -e 옵션
      - ORACLE_ALLOW_REMOTE=true

#    command: # 명령어 실행
#      - --character-set-server=utf8mb4
#      - --collation-server=utf8mb4_unicode_ci
    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - database:/var/lib/oracle # -v 옵션 (다렉토리 마운트 설정)