spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: moving-out-common
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: oracle
    driverClassName: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto: create
#      naming:
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        format_sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect