server:
  port: 8080

spring:
  application:
    name: moving-out-api
  config:
    activate:
      on-profile: default

##############################################
#  Springboot admin
############################################
  boot:
    admin:
      client:
        url: http://localhost:8090
        instance:
          service-url: http://localhost:8080
##############################################
#  Spring boot actuator
############################################
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*" # TODO : Security 설정 적용 후 해당 속성 조정 필요.
    health:
      show-details: always